---
title: "STA325 Final Project"
author: "Alice Liao, Revo Tesha, Salvador, Cindy, Evelyn "
date: "10/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(cowplot)
library(janitor)
library(nnet)
library(caret)
library(broom)
library(tree)
library(brms)
set.seed(10)
```

## Data

### Drug poisoning dataset
```{r}
common_names = c("WAYNE", "MARION","HANCOCK", "WOOD", "JEFFERSON", "LOGAN", 
                 "PUTNAM", "MERCER", "FAYETTE", "HARRISON", "JACKSON", "MONROE","MORGAN" )
# load original dataset
death.wv = read.csv("data/Drug_Poisoning_Mortality_by_County.csv", header = TRUE) %>%
  mutate(COUNTY = str_to_upper(str_replace_all(County, " County, WV", "")),
        COUNTY = as.factor(ifelse(COUNTY %in% common_names, paste0(COUNTY, "_WV"), COUNTY)))
death.oh = read.csv("data/NCHS_-_Drug_Poisoning_Mortality_by_County__United_Statesoh.csv", 
                     header = TRUE, as.is = TRUE) %>%
  mutate(Population = as.numeric(gsub(",", "", Population, fixed=TRUE)),
         COUNTY = str_to_upper(str_replace_all(County, " County, OH", "")),
         COUNTY = as.factor(ifelse(COUNTY %in% common_names, paste0(COUNTY, "_OH"), COUNTY)))
death0 =  rbind(death.wv, death.oh) %>%
    rename(est_death_rate = Estimated.Age.adjusted.Death.Rate..16.Categories..in.ranges.)
# est_death_rate is age adjusted death rate, deaths per 100,000 U.S. standard population for 2000
```

```{r}
# data cleaning
thirty_plus = which(death0$est_death_rate == "30+")
imputed_deaths = as.character(death0$est_death_rate)
for(idx in thirty_plus){
  random_death_rate = round(runif(1, 30, 957), 0) # this works now but I think we could
  # also use another (truncated) distribution that reflects distribution of adjusted death rates in
  # wv. I (revo) can look into this later if we want to.
  new_interval = paste0(random_death_rate, "-", random_death_rate)
  imputed_deaths[idx] = as.character(new_interval)
}
death0$imput_est_death_rate_num = imputed_deaths
death0$imput_est_death_rate_cat = as.factor(imputed_deaths)
death1 <- death0 %>%
  separate(imput_est_death_rate_num, c("lower_rate", "upper_rate"), sep = "-") %>%
  mutate(imput_est_death_rate_num = (as.numeric(lower_rate) + as.numeric(upper_rate))/2,
         pop_num = as.numeric(Population)) %>%
  mutate(est_death_rate_cat = case_when(
    est_death_rate %in% c("2-3.9","4-5.9","6-7.9") ~ "cat_1",
    est_death_rate %in% c("8-9.9", "10-11.9","12-13.9") ~ "cat_2",
    est_death_rate %in% c("14-15.9","16-17.9", "18-19.9") ~ "cat_3",
    est_death_rate %in% c("20-21.9", "22-23.9","24-25.9") ~ "cat_4",
    est_death_rate %in% c("26-27.9","28-29.9") ~ "cat_5",
    est_death_rate == "30+" ~ "cat_6"
  )) %>%
  select(State, COUNTY, FIPS,Year, imput_est_death_rate_num, est_death_rate_cat, Population) %>%
  mutate(est_death_rate_cat=factor(est_death_rate_cat, levels = c( "cat_1","cat_2","cat_3","cat_4","cat_5", "cat_6")))
```


```{r}
death1 %>%
  select(Year, est_death_rate_cat,COUNTY) %>%
  mutate(Year = as.factor(Year),
         est_death_rate_cat = as.factor(est_death_rate_cat)) %>%
  ggplot(., aes(x = Year, fill = est_death_rate_cat)) +
  geom_bar(position=position_dodge())  +
  # facet_grid(as.factor(COUNTY) ~.)
```

### Arcos dataset
```{r}
arcos0a = read.csv("arcos-wv-statewide-itemizedexcel.csv", header = TRUE) %>%
  mutate(BUYER_COUNTY = as.character(BUYER_COUNTY),
         BUYER_COUNTY = as.factor(ifelse(BUYER_COUNTY %in% common_names, paste0(BUYER_COUNTY, "_WV"),
                               BUYER_COUNTY)))
acros0b = read_tsv("arcos-oh-statewide-itemized.tsv", col_names = TRUE) %>%
  mutate(BUYER_COUNTY = as.character(BUYER_COUNTY),
         BUYER_COUNTY = as.factor(ifelse(BUYER_COUNTY %in% common_names, paste0(BUYER_COUNTY, "_OH"),
                               BUYER_COUNTY)))
# create subset with less variables
arcos1 <- rbind(arcos0a, acros0b) %>%
  transmute(Year = as.numeric(str_sub(TRANSACTION_DATE, -4, -1)),
            REPORTER_NAME = as.factor(REPORTER_NAME), # name of distributor/manufacturer who reported the transaction to DEA
            REPORTER_STATE = as.factor(REPORTER_STATE),
            BUYER_TYPE = as.factor(BUYER_BUS_ACT), # types of retailers
            BUYER_NAME = as.factor(BUYER_NAME),
            BUYER_ADDRESS = as.factor(BUYER_ADDRESS1),
            BUYER_CITY = as.factor(BUYER_CITY),
            BUYER_STATE = as.factor(BUYER_STATE),
            BUYER_ZIP = as.factor(BUYER_ZIP),
            BUYER_COUNTY = as.factor(BUYER_COUNTY),
            DRUG_CODE = as.factor(DRUG_CODE),
            DRUG_NAME = as.factor(DRUG_NAME),
            QUANTITY = as.integer(QUANTITY),
            TOTAL_ACTIVE_WT = as.numeric(CALC_BASE_WT_IN_GM), # weight of total active drug in each transaction, in grams 
            DOSAGE_UNIT= as.numeric(DOSAGE_UNIT), # num of tablets in each unit
            PRODUCT_NAME = as.factor(Product_Name),
            MEASURE = as.factor(Measure), # form of drugs - in WV dataset, all are pills
            EQU_MORPHINE = as.numeric(MME_Conversion_Factor), # equivalent amt of morphine in mg
            MANUFACTURER = as.factor(Revised_Company_Name), # entity that manufactured, distributed or 
            # relabeled the drug product in the transaction
            DOS_STR = as.numeric(dos_str)) # strength of each dosage in mg (in this case, strength in each tablet)
```

```{r}
# death rate EDA
death1 %>%
  ggplot()+
  facet_wrap(. ~ COUNTY) +
  geom_col(aes(x = Year, y = Population)) +
  labs(title = "County Population from 2006 - 2012, WV") # population is almost constant over the seven years
death1 %>%
  ggplot()+
  facet_wrap(. ~ COUNTY) +
  geom_col(aes(x = Year, y = est_death_rate_cat)) +
  # geom_hline(yintercept = median(death_rate))+
  labs(title = "Drug-related Death Rate from 2006 - 2012, WV") # death rate in general has a upward trend
# arcos original dataset EDA 
# total active weight by county and drug name
arcos_wt_eda <- arcos1 %>%
  group_by(BUYER_COUNTY, Year) %>%
  summarise(active_wt_by_year = sum(TOTAL_ACTIVE_WT))
# head(arcos_wt_eda)
arcos_wt_eda %>%
  ggplot() +
  facet_wrap(. ~ BUYER_COUNTY) +
  geom_col(aes(x = Year, y = active_wt_by_year)) +
  labs(title = "Total Active Drug Weight (in grams) from 2006-2012 by County, WV") # total active wt in general has an upward trend
```

### Income dataset
```{r}
wv_income_data = read.csv("data/wv_median_household_income_data.csv") %>%
  filter(year == 2012) %>%
  filter(county != "West Virginia") %>%
  mutate(county = str_to_upper(county)) %>%
  dplyr::select(county, median_income) %>%
  mutate(county = as.factor(ifelse(county %in% common_names, paste0(county, "_WV"),
                               county)))
oh_income_data = read.csv("data/ohio_median_household_income_data.csv") %>%
  dplyr::select(GCT_STUB.display.label.1, HC01) %>%
  clean_names() %>% # need library(janitor)
  transmute(county = str_trim(str_to_upper(str_remove_all(as.character(gct_stub_display_label_1), " County"))),
            median_income = as.numeric(as.character(hc01))) %>%
  slice(-1,-2) %>%
  mutate(county = as.factor(ifelse(county %in% common_names, paste0(county, "_OH"),
                               county)))
income_data = rbind(wv_income_data, oh_income_data)
```

### Party affiliation
```{r}
wv_pol_affiliation <- read.csv("data/wv_politics.csv") %>%
  mutate(County = as.character(State),
         County = ifelse(County == "TAYLOR,", "TAYLOR", County),
         County = as.factor(ifelse(County %in% common_names, paste0(County, "_WV"),
                               County))) %>%
  select(-State)

oh_pol_affilitation <- read.csv("data/oh_politics.csv") %>%
  mutate(Political.affiliation = Party.affiliation,
         County = str_trim(str_to_upper(State))) %>%
  filter(County != "") %>%
  mutate(County = as.character(County),
         County = as.factor(ifelse(County %in% common_names, paste0(County, "_OH"),
                               County))) %>%
  select(-State, -Party.affiliation)

pol_affiliation <- rbind(wv_pol_affiliation, oh_pol_affilitation)
```

### Create additional variables
```{r}
# arcos collapse by county, create relevant variables, only consider 2012
arcos2012 <- arcos1 %>%
  filter(Year == "2012")

# calculate total active weight in each county 2012
all_act_wt <- arcos2012 %>%
  group_by(BUYER_COUNTY) %>%
  summarise(all_active_wt = sum(TOTAL_ACTIVE_WT))

# New Variable: % oxycodone and % hydrocodone in each count
oxy_sum <- arcos2012%>%
  filter(DRUG_NAME == "OXYCODONE") %>%
  group_by(BUYER_COUNTY) %>%
  summarise(oxy_wt = sum(TOTAL_ACTIVE_WT))
hyd_sum <- arcos2012%>%
  filter(DRUG_NAME == "HYDROCODONE") %>%
  group_by(BUYER_COUNTY) %>%
  summarise(hyd_wt = sum(TOTAL_ACTIVE_WT))

perc_drug <- merge(oxy_sum, hyd_sum, by.x = "BUYER_COUNTY", by.y = "BUYER_COUNTY", all.x = TRUE) %>%
  mutate(perc_oxy = round(oxy_wt/(oxy_wt+hyd_wt),3)*100,
         perc_hyd = 100-perc_oxy)

# New Variable: most common distribution channel (by number of transactions) in each county
most_common_dist <- arcos2012 %>%
  group_by(BUYER_COUNTY) %>%
  summarise(perc_retail = sum(BUYER_TYPE== "RETAIL PHARMACY")/n(), 
            perc_chain = sum(BUYER_TYPE == "CHAIN PHARMACY")/n(),
            perc_practitioner = sum(BUYER_TYPE %in% c("PRACTITIONER", "PRACTITIONER-DW/100",
                                                     "PRACTITIONER-DW/275","PRACTITIONER-DW/30"))/n())%>%
  mutate(most_dist_channel = case_when(
    perc_retail >= perc_chain & perc_retail >= perc_practitioner ~ "RETAIL PHARMACY",
    perc_chain >=  perc_retail & perc_chain >= perc_practitioner ~ "CHAIN PHARMACY",
    TRUE ~ "PRACTITIONER")) 

# New Variable: number of pharmacies in each county that buy drugs from manufacturers
pharm_num <- arcos2012 %>%
  group_by(BUYER_COUNTY) %>%
  summarise(pharmacy_num = n_distinct(BUYER_ADDRESS))

# New Variable: number of drug manufacturers/distributers that supply drugs to local pharmacies
num_of_distr <- arcos2012 %>%
  group_by(BUYER_COUNTY, REPORTER_NAME) %>%
  summarise(dist_num = n_distinct(REPORTER_NAME)) %>%
  group_by(BUYER_COUNTY) %>%
  summarise(distr_num = sum(dist_num))

# New Variable: market dominance, "yes" - if two pharmarcies in a county account for more than 50% of total active weight of drugs
market_dom <- arcos2012 %>%
  group_by(BUYER_COUNTY, BUYER_ADDRESS) %>%
  summarise(pharm_wt = sum(TOTAL_ACTIVE_WT)) %>%
  mutate(market_share = round(pharm_wt/sum(pharm_wt),3)*100) %>%
  arrange(BUYER_COUNTY, desc(market_share)) %>%
  mutate(dominance = "No")
for(county in unique(market_dom$BUYER_COUNTY)){
  index <- which(market_dom$BUYER_COUNTY == county)
  c.df <- market_dom %>%
    filter(BUYER_COUNTY == county)
  if(sum(c.df$market_share[1:2]) >50 & length(c.df$market_share) >=2){
    market_dom$dominance[index] <- "Yes"}
  else if(length(c.df$market_share)==1){
    market_dom$dominance[index] <- "Yes"}
}
market_dom2 <- market_dom %>%
  select(BUYER_COUNTY, dominance) %>%
  distinct()
```

### Merge datasets
#### EACH ROW OF oh_wv_all IS STILL A TRANSACTION - DO NOT USE THIS

```{r eval=FALSE}
# merge arcos1 and death1
arcos_and_death <- merge(arcos1, death1, by.x = "BUYER_COUNTY", by.y = "COUNTY", all.x = TRUE)
# merge income with arcos and death data
arcos_death_and_income <- merge(arcos_and_death, income_data, by.x = "BUYER_COUNTY", by.y = "county", all.x = TRUE)
# merge arcos_death_and_income with policatal affiliation data
all0 <- merge(arcos_death_and_income, pol_affiliation, by.x = "BUYER_COUNTY", by.y = "County", all.x = TRUE)
# merge with population data, create total active weight in county per person
TAWICPP <- all0 %>%
  group_by(BUYER_COUNTY) %>%
  summarise(county_total_wt=sum(TOTAL_ACTIVE_WT), Population=first(Population)) %>%
  mutate(act_wt_person_county = county_total_wt/Population) %>%
  dplyr::select(-Population)
oh_wv_all = merge(all0, TAWICPP, by.x = "BUYER_COUNTY", by.y = "BUYER_COUNTY", all.x = TRUE) %>%
  filter(Year == 2012) # %>% # only consider 2012
  # filter(!is.na(act_wt_person_county))
```

#### EACH ROW IS A COUNTY
```{r}
# recreate new arcos dataset - 2012 data with relevant variables
arcos2.1 <- merge(all_act_wt, perc_drug, by.x = "BUYER_COUNTY", by.y = "BUYER_COUNTY", all.x = TRUE)
arcos2.2 <- merge(arcos2.1, most_common_dist, by.x = "BUYER_COUNTY", by.y = "BUYER_COUNTY", all.x = TRUE)
arcos2.3 <- merge(arcos2.2, pharm_num, by.x = "BUYER_COUNTY", by.y = "BUYER_COUNTY", all.x = TRUE)
arcos2.4 <- merge(arcos2.3, num_of_distr, by.x = "BUYER_COUNTY", by.y = "BUYER_COUNTY", all.x = TRUE)
arcos_county <- merge(arcos2.4, market_dom2, by.x = "BUYER_COUNTY", by.y = "BUYER_COUNTY", all.x = TRUE)

death2012 <- death1 %>%
  filter(Year == "2012")
  
# merge arcos_county and death2012
arcos_and_death2012 <- merge(arcos_county, death2012, by.x ="BUYER_COUNTY", 
                             by.y = "COUNTY", all.x = TRUE) %>%
  select(-FIPS)

# merge income with arcos_county and death2012 and income data
arcos_death_and_income2012 <- merge(arcos_and_death2012, income_data, 
                                   by.x = "BUYER_COUNTY", by.y = "county", all.x = TRUE)
# merge arcos_death_and_income2012 with policatal affiliation data
all2012 = merge(arcos_death_and_income2012, pol_affiliation, 
                by.x = "BUYER_COUNTY", by.y = "County", all.x = TRUE)

# merge with population data, create total active weight in county per person
oh_wv_2012 <- all2012 %>%
  mutate(act_wt_person_county = all_active_wt/Population,
         political_aff = Political.affiliation,
         pharmacy_num_ptt = round((10000*pharmacy_num/Population),3),
         distr_num_ptt = round((10000*distr_num/Population),3),
         most_dist_channel = as.factor(most_dist_channel),
         dominance = as.factor(dominance)) %>%
  select(-Political.affiliation)
```

```{r}
# export oh_wv_2012 to csv file
write_csv(oh_wv_2012, "data/oh_wv_2012.csv")
```
